### ISSUE TITLE
Pre-Release 1

### ISSUE THREAD

**Issue by hilakista** [ob-vss-ss18/ppl-stock#11]
Siehe [Pre-Release 1](https://github.com/ob-vss-ss18/ppl-core/wiki/Pre-Release-1)

**Comment by DManstrator** [comment]
Ist anvisiert, wenn PR #12 durchgeht, geben wir `Hello World!` zurück.
Link in Heroku tragen wir noch ein,  Danke für die Erinnerung!

**Comment by konopac** [comment]
Das Programm läuft jetzt unter der URL: https://ppl-stock.herokuapp.com/stock

**Comment by konopac** [comment]
Die Readme Datei wurde ebenfalls um die URL ergänzt.
