### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by konopac** [ob-vss-ss18/ppl-stock#13]
Die App soll als Go-App von Heroku erkannt werden und diese deployen, damit "Hello World" aufgerufen werden kann.

**Comment by DManstrator** [comment]
URL geändert zu https://ppl-stock.herokuapp.com/mit https://github.com/ob-vss-ss18/ppl-stock/commit/733576b53f80c89775c6d5c1b5eee1e385d4d5f2
