### ISSUE TITLE
Basic view for database contents

### ISSUE THREAD

**Issue by Ghouz** [ob-vss-ss18/ppl-stock#21]
Es wurde ja gesagt, dass er den Bestand sehen möchte. (Was wurde ausgeleiht/ist noch verfügbar, etc.)

Anstatt des Hello worlds könnte man anfangs einfach mal beispielhaft Inhalte aus der integrierten Datenbank in einer HTML tabelle darstellen.

Später sollte die Seite eventuell nur für authentifizierte Nutzer zugänglich sein (sollte dann wahrscheinlich ein eigenes Issue sein)

**Comment by konopac** [comment]
Sorry, falls ich was falsch verstanden habe, aber wir sollen doch nur die Daten liefern, keine Oberfläche machen, oder? Ich frage, weil du von HTML-Tabellen schreibst.

**Comment by DManstrator** [comment]
Was ist jetzt der Stand der Dinge? Returnen wir JSON-Objekte, welcher der Client selbst noch parsen muss?
