### ISSUE TITLE
Grant Admin Access to Members

### ISSUE THREAD

**Issue by DManstrator** [ob-vss-ss18/ppl-stock#3]
@truenicfel Before we are able to do things like merging, etc., please give Admin Rights to the following people:
- [Michael Eggers](https://github.com/michaeleggers)
- Sven Schatter
- [Philipp Konopac](https://github.com/konopac)
- Jannes Kretschmer
- [Daniel Gabl](https://github.com/DManstrator)

Couldn't find other GitHub Accounts, sry.

**Comment by truenicfel** [comment]
Hey @DManstrator 
würdest du den Ansprechpartner machen? Ich schaffe es zeitlich nicht wegen anderen Vorlesungen... Kontaktiere mich deswegen am besten per mail: dassler@hm.edu

Zum eigentlichen issue:
Ich kann keine admin rechte vergeben. Ich kann nicht mal selbst pull requests bestätigen (vielleicht liegt das aber daran, dass die checks fehlschlagen). Vielleicht hat Herr Braun die Rechte nicht an mich vergeben...

**Comment by DManstrator** [comment]
Muss selbst einmal schauen, für's erste kann ich's auf jeden Fall machen, damit wir zumindest einmal starten können.

@obcode Können Sie uns vielleicht helfen?

**Comment by obcode** [comment]
@truenicfel Sie haben eine E-Mail von GitHub bekommen in der ein Link ist über den Sie die Mitgliedschaft in der Organisation annehmen (alle anderen auch). Wenn Sie das tun, haben Sie hier Adminrechte und können die anderen hinzufügen. Gehen Sie mal im Browser auf die Organisation. Da geht das, glaube ich, auch. HTH

**Comment by truenicfel** [comment]
Hat geklappt. Vielen Dank für die Hilfe @obcode.

**Comment by DManstrator** [comment]
Die E-Mails haben nur diejenigen bekommen, die das Repository "beantragt" haben.
Und füge bitte keine Mentions bei Edits hinzu, GitHub kann das nicht handeln und benachrichtigt dann diese Person nicht.

**Comment by truenicfel** [comment]
4/5 habe ich adden können. Von Jannes Kretschmer fehlt mir der github account.
Vielleicht kann @konopac helfen?

**Comment by truenicfel** [comment]
Everyone is invited...
