### ISSUE TITLE
Implement basic REST-API

### ISSUE THREAD

**Issue by konopac** [ob-vss-ss18/ppl-stock#38]
After the example of #36, all the REST-APIs defined in the uploaded PDFs should be implemented. No logic, access to services or database yet, only returning a basic data sample.

Example:
GET SkiById -> return { nr: 123, marke: "Fischer", ... }

**Comment by konopac** [comment]
PDFs are uploaded here #9

**Comment by Ghouz** [comment]
Nachdem wir nicht mit REST sondern GraphQL arbeiten sollen und das so weit auch schon implementiert ist, mache ich hier mal zu.
