### ISSUE TITLE
Access Data from Datebase via. URL

### ISSUE THREAD

**Issue by DManstrator** [ob-vss-ss18/ppl-stock#41]
Since I saw no way to access data from the repository via. the URL only (e. g. `http://localhost:8080/graphql?query={Ski(id:10){brand id useCase}}` or similar), maybe we should implement that for an easy and natural access.

**Comment by DManstrator** [comment]
Es macht Sinn, die anderen Services müssen unseren Service irgendwie ansprechen können, die URL ist aber falsch, das stimmt.

Besser wäre so etwas: `http://localhost:8080/graphql?type=ski&id=10`, wir bekommen die Parameter, bauen die GraphQL-Anfrage und geben die Daten aus der Anfrage zurück. Ändere es gerade in das um.

**Comment by Ghouz** [comment]
Du liegst falsch.

**Comment by Ghouz** [comment]
https://graphql.org/learn/

**Comment by Ghouz** [comment]
graphql macht man nicht über GET parameter........

**Comment by Ghouz** [comment]
Mach was du meinst :)

**Comment by DManstrator** [comment]
Hab jetzt einfach noch einmal mit Herrn Braun geredet, hab vergessen bzw. nicht gewusst, dass an uns bereits eine GraphQL-Anfrage geschickt wird, hab gedacht, dass die Services unsere URL mit den Daten, die sie wollen, aufrufen (siehe Link) und wir holen die Daten. Müssten wir dann noch so etwas wie einen GraphQL-Empfänger bauen oder ist das schon irgendwo implementiert / festgehalten?

**Comment by Ghouz** [comment]
Ist schon implementiert...

**Comment by Ghouz** [comment]
Es müssen eigentlich nur noch die entsprechenden Queries (die wir vom Core Team brauchen) deklariert und dann so sachen wie loadSkiFromDatabase() (zurzeit in schema.go) implementiert werden.
