### ISSUE TITLE
PDFs mit Beispiel-Bestand

### ISSUE THREAD

**Issue by obcode** [ob-vss-ss18/ppl-stock#9]
Ich habe gerade 2 PDFs in das ppl-core-Repo committet:

https://github.com/ob-vss-ss18/ppl-core/commit/c0290d0c733be790d44f4a8b594e29ba649a9172

**Comment by DManstrator** [comment]
Werde mich darum kümmern, eine Datenstruktur zu schaffen und die Elemente über die Main hinzuzufügen, wird nur diese Woche wegen Abgaben zu Computergrafik & Bildverarbeitung und Embedded Computing schwer, ich werde mich spätestens beim nächsten Praktikumstermin (24.04.2018, 11:45 Uhr) darum kümmern, wenn es bis dahin ausreichend ist.

**Comment by obcode** [comment]
Klar. Wollte die Info nur gleich weiter geben.

**Comment by DManstrator** [comment]
Gut zu wissen, vielen Dank!
